### ISSUE TITLE
ModuleNotFoundError: No module named 'mido' even though I just pip installed it on Windows

### ISSUE THREAD

**Issue by adithraghavs** [Conchylicultor/MusicGenerator#15]
When I run python main.py, it shows me an error like this:
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    import deepmusic
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\__init__.py", line 3, in <module>
    from deepmusic.composer import Composer
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\composer.py", line 31, in <module>
    from deepmusic.musicdata import MusicData
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\musicdata.py", line 27, in <module>
    from deepmusic.midiconnector import MidiConnector
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\midiconnector.py", line 20, in <module>
    import mido  # Midi lib
ModuleNotFoundError: No module named 'mido'
```

When I pip install it, it installs correctly:
```
Collecting mido
  Downloading mido-1.2.9-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 100 kB/s
Installing collected packages: mido
Successfully installed mido-1.2.9
```
But when I run main.py again:
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    import deepmusic
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\__init__.py", line 3, in <module>
    from deepmusic.composer import Composer
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\composer.py", line 31, in <module>
    from deepmusic.musicdata import MusicData
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\musicdata.py", line 27, in <module>
    from deepmusic.midiconnector import MidiConnector
  File "C:\Users\User\freekode-projects\MusicGenerator\deepmusic\midiconnector.py", line 20, in <module>
    import mido  # Midi lib
ModuleNotFoundError: No module named 'mido'
```
I'm on Windows 10.
I'm still 12 years old, so I might have missed telling you some information, and sorry for that.
Please help, and thank you in advance.

**Comment by Conchylicultor** [comment]
I think you might not be installing in the right environement (maybe use `pip3` instead of `pip`). You can see that whether pip it is working or not by running `python -c "import mido"`.

But more generally, this project isn't really working (or was left in a bad state), and is fairly old, so I would suggest trying out other project instead.

**Comment by adithraghavs** [comment]
Okay, thanks a lot!
