### ISSUE TITLE
attempting to use tensorflow-1.3 - but getting error - Trying to share variable rnn_decoder/KeyboardCell/Decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (1024, 2048) and found shape (525, 2048).

### ISSUE THREAD

**Issue by johndpope** [Conchylicultor/MusicGenerator#8]
I did read readme and that it's only supposed to work on tensorflow 1.0

I updated the references to older methods 

<img width="1239" alt="screen shot 2017-09-06 at 11 48 58 am" src="https://user-images.githubusercontent.com/289994/30121338-660a9b88-92f9-11e7-9291-004f6898036e.png">
<img width="1145" alt="screen shot 2017-09-06 at 11 48 54 am" src="https://user-images.githubusercontent.com/289994/30121339-67b5d592-92f9-11e7-82aa-b1fdfd57311f.png">

but now I'm getting 

python main.py
Welcome to DeepMusic v0.1 !

**TensorFlow detected: v1.3.0**

Current parameters:
glob_step: 0
keep_all: False
dataset_tag: ragtimemusic
sample_length: 40
hidden_size: 512
num_layers: 2
target_weights: linear
scheduled_sampling: none
batch_size: 64
save_every: 1000
ratio_dataset: 0.9
testing_curve: 10
batch_builder: relative
learning_rate: cst
enco_cell: identity
deco_cell: lstm
loop_processing: sample_softmax

Restoring dataset from /Users/jpope/Documents/tensorflowWorkspace/MusicGenerator/data/samples/ragtimemusic-relative.pkl...
Loaded: 1 songs (0 train/1 test)
Model creation...
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    composer.main()
  File "/Users/jpope/Documents/tensorflowWorkspace/MusicGenerator/deepmusic/composer.py", line 166, in main
    self.model = Model(self.args)
  File "/Users/jpope/Documents/tensorflowWorkspace/MusicGenerator/deepmusic/model.py", line 160, in __init__
    self._build_network()
  File "/Users/jpope/Documents/tensorflowWorkspace/MusicGenerator/deepmusic/model.py", line 215, in _build_network
    loop_function=loop_rnn
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 152, in rnn_decoder
    output, state = cell(inp, state)
  File "/Users/jpope/Documents/tensorflowWorkspace/MusicGenerator/deepmusic/keyboardcell.py", line 76, in __call__
    next_keyboard, next_state_deco = self.decoder.get_cell(prev_keyboard, (next_state_enco, prev_state[1]))
  File "/Users/jpope/Documents/tensorflowWorkspace/MusicGenerator/deepmusic/modules/decoder.py", line 200, in get_cell
    next_output, next_state = self.rnn_cell(prev_input, prev_states[1])
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 938, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 774, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 401, in call
    concat = _linear([inputs, h], 4 * self._num_units, True)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1039, in _linear
    initializer=kernel_initializer)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1405, in wrapped_custom_getter
    *args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/Users/jpope/miniconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 669, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable rnn_decoder/KeyboardCell/Decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (1024, 2048) and found shape (525, 2048).

**Comment by johndpope** [comment]
this link - it's not immediately obvious how to update this code
https://github.com/udacity/deep-learning/issues/132

(this didn't work)
rnn_cell = tf.nn.rnn_cell.MultiRNNCell([rnn_cell() for i in range(self.args.num_layers)], state_is_tuple=True)

**Comment by EvilMudkip** [comment]
I have the same problem :'(

`ValueError: Trying to share variable rnn_decoder/KeyboardCell/Decoder/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (1024, 2048) and found shape (525, 2048).`

@johndpope How do I update the code? Which file and which line? Please help...

**Comment by EMCP** [comment]
this is a matrix mismatch error..

seems the keyboardcell has a hardcoding somewhere that needs to be adjusted?

**Comment by musca1997** [comment]
same problem, have you solved it yet?

**Comment by harperjuanl** [comment]
same problem, have you solved it yet?

**Comment by johndpope** [comment]
Closing
